-- PostgreSQL 16 service store. All temporal values use timestamptz.
-- Schedule/telematics payloads are staging JSON until ETL confirms source mapping.
BEGIN;
CREATE TABLE IF NOT EXISTS public.routes (
 route_id varchar(10) PRIMARY KEY, name varchar(100) NOT NULL, color varchar(7),
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.stops (
 stop_id varchar(20) PRIMARY KEY, name varchar(200) NOT NULL,
 latitude numeric(10,8) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
 longitude numeric(11,8) NOT NULL CHECK (longitude BETWEEN -180 AND 180),
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.route_stops (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 route_id varchar(10) NOT NULL REFERENCES public.routes(route_id),
 direction varchar(20) NOT NULL, stop_id varchar(20) NOT NULL REFERENCES public.stops(stop_id),
 stop_order integer NOT NULL CHECK (stop_order > 0),
 UNIQUE (route_id,direction,stop_id), UNIQUE (route_id,direction,stop_order)
);
CREATE TABLE IF NOT EXISTS public.route_geometry (
 route_id varchar(10) NOT NULL REFERENCES public.routes(route_id),
 direction varchar(20) NOT NULL, geometry jsonb NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(route_id,direction)
);
CREATE TABLE IF NOT EXISTS public.validations (
 tran_no text NOT NULL, tran_date_time timestamptz NOT NULL,
 route_id varchar(10) REFERENCES public.routes(route_id),
 stop_id varchar(20) REFERENCES public.stops(stop_id),
 payload jsonb NOT NULL DEFAULT '{}'::jsonb, ingested_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(tran_no,tran_date_time)
) PARTITION BY RANGE (tran_date_time);
CREATE TABLE IF NOT EXISTS public.validations_default PARTITION OF public.validations DEFAULT;
CREATE INDEX IF NOT EXISTS validations_time_idx ON public.validations(tran_date_time);
CREATE INDEX IF NOT EXISTS validations_route_stop_time_idx ON public.validations(route_id,stop_id,tran_date_time);
CREATE TABLE IF NOT EXISTS public.schedule (
 schedule_row_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 source_row_id text, service_date date,
 route_id varchar(10) REFERENCES public.routes(route_id),
 stop_id varchar(20) REFERENCES public.stops(stop_id),
 payload jsonb NOT NULL, source text NOT NULL, fetched_at timestamptz NOT NULL DEFAULT now(),
 ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS schedule_route_date_idx ON public.schedule(route_id,service_date);
CREATE TABLE IF NOT EXISTS public.telematics (
 telematics_row_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 source_row_id text, event_ts timestamptz,
 route_id varchar(10) REFERENCES public.routes(route_id),
 stop_id varchar(20) REFERENCES public.stops(stop_id),
 payload jsonb NOT NULL, source text NOT NULL, fetched_at timestamptz NOT NULL DEFAULT now(),
 ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS telematics_route_time_idx ON public.telematics(route_id,event_ts);
CREATE TABLE IF NOT EXISTS public.target_hourly (
 route_id varchar(10) NOT NULL REFERENCES public.routes(route_id),
 stop_id varchar(20) NOT NULL REFERENCES public.stops(stop_id),
 ts_hour timestamptz NOT NULL, passengers numeric(14,3) NOT NULL CHECK(passengers>=0),
 updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(route_id,stop_id,ts_hour)
);
CREATE INDEX IF NOT EXISTS target_hourly_time_idx ON public.target_hourly(ts_hour);
CREATE TABLE IF NOT EXISTS public.ext_weather_hourly (
 location_key text NOT NULL, ts_hour timestamptz NOT NULL, payload jsonb NOT NULL,
 source text NOT NULL, fetched_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(location_key,ts_hour,source)
);
CREATE TABLE IF NOT EXISTS public.ext_traffic_hourly (
 route_id varchar(10) NOT NULL REFERENCES public.routes(route_id),
 ts_hour timestamptz NOT NULL, payload jsonb NOT NULL, source text NOT NULL,
 fetched_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(route_id,ts_hour,source)
);
CREATE TABLE IF NOT EXISTS public.ext_calendar_days (
 calendar_date date NOT NULL, payload jsonb NOT NULL, source text NOT NULL,
 fetched_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(calendar_date,source)
);
CREATE TABLE IF NOT EXISTS public.ext_events (
 event_id text NOT NULL, starts_at timestamptz, ends_at timestamptz,
 payload jsonb NOT NULL, source text NOT NULL, fetched_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(event_id,source),
 CHECK(ends_at IS NULL OR starts_at IS NULL OR ends_at>=starts_at)
);
CREATE TABLE IF NOT EXISTS public.features_hourly (
 route_id varchar(10) NOT NULL REFERENCES public.routes(route_id),
 stop_id varchar(20) NOT NULL REFERENCES public.stops(stop_id),
 ts_hour timestamptz NOT NULL, features jsonb NOT NULL,
 generated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(route_id,stop_id,ts_hour)
);
CREATE INDEX IF NOT EXISTS features_hourly_time_idx ON public.features_hourly(ts_hour);
CREATE TABLE IF NOT EXISTS public.forecast_runs (
 run_id uuid PRIMARY KEY, model_version text NOT NULL, horizon text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(),
 status text NOT NULL DEFAULT 'completed' CHECK(status IN ('running','completed','failed')),
 metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE TABLE IF NOT EXISTS public.forecasts (
 forecast_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 run_id uuid NOT NULL REFERENCES public.forecast_runs(run_id), horizon text NOT NULL,
 ts timestamptz NOT NULL, route_id varchar(10) REFERENCES public.routes(route_id),
 stop_id varchar(20) REFERENCES public.stops(stop_id),
 value numeric(14,3) NOT NULL CHECK(value>=0), created_at timestamptz NOT NULL DEFAULT now(),
 CHECK(route_id IS NOT NULL OR stop_id IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS forecasts_horizon_route_ts_idx ON public.forecasts(horizon,route_id,ts);
CREATE INDEX IF NOT EXISTS forecasts_horizon_stop_ts_idx ON public.forecasts(horizon,stop_id,ts);
CREATE TABLE IF NOT EXISTS public.model_metrics (
 metric_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 model_version text NOT NULL, horizon text NOT NULL,
 route_id varchar(10) REFERENCES public.routes(route_id), slice text NOT NULL,
 wape numeric(10,6) CHECK(wape>=0), measured_at timestamptz NOT NULL DEFAULT now(),
 details jsonb NOT NULL DEFAULT '{}'::jsonb
);
COMMIT;
