/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tram routes */
        get: operations["listRoutes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get route details with stops */
        get: operations["getRoute"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{id}/geometry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get route geometry (GeoJSON) */
        get: operations["getRouteGeometry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time series / aggregated forecast */
        get: operations["getForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Map points with load per stop for a given hour */
        get: operations["getForecastMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Heatmap stop x hour */
        get: operations["getForecastHeatmap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast/kpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** KPI for current filters */
        get: operations["getForecastKpi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export forecast as CSV or XLSX */
        get: operations["exportForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/factors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coefficient presets and external sources */
        get: operations["getFactors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model metadata and metrics */
        get: operations["getModelInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger forecast recompute (admin) */
        post: operations["recomputeForecast"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch client telemetry */
        post: operations["postTelemetry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved coefficient scenarios */
        get: operations["listUserScenarios"];
        put?: never;
        /** Save coefficient scenario */
        post: operations["createUserScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-scenarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete scenario */
        delete: operations["deleteUserScenario"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Horizon: "day" | "month" | "year";
        /** @enum {string} */
        Grouping: "route" | "stop" | "segment";
        /** @enum {string} */
        LoadLevel: "low" | "medium" | "high";
        ApiError: {
            message: string;
            request_id: string;
            code?: string;
        };
        ForecastMeta: {
            external_data_stale?: boolean;
            /** @description True for month/year horizons */
            estimated?: boolean;
            request_id?: string;
        };
        Coefficients: {
            /** @default 1 */
            k_weather: number;
            /** @default 1 */
            k_event: number;
            /** @default 1 */
            k_season: number;
            /** @default 1 */
            k_traffic: number;
        };
        RouteSummary: {
            id: string;
            name: string;
            number: string;
        };
        RouteListResponse: {
            items: components["schemas"]["RouteSummary"][];
        };
        Stop: {
            id: string;
            name: string;
            lat: number;
            lon: number;
            sequence: number;
        };
        RouteDetail: components["schemas"]["RouteSummary"] & {
            stops: components["schemas"]["Stop"][];
        };
        RouteGeometry: {
            route_id: string;
            /** @enum {string} */
            type: "LineString";
            coordinates: number[][];
        };
        TimeSeriesPoint: {
            ts: string;
            baseline: number;
            adjusted: number;
            actual?: number | null;
        };
        ForecastResponse: {
            series: components["schemas"]["TimeSeriesPoint"][];
            meta: components["schemas"]["ForecastMeta"];
            effect?: components["schemas"]["CoefficientEffect"];
        };
        CoefficientEffect: {
            delta_percent?: number;
            delta_passengers?: number;
        };
        MapStopLoad: {
            stop_id: string;
            name: string;
            lat: number;
            lon: number;
            load: number;
            level: components["schemas"]["LoadLevel"];
            sequence: number;
            baseline_load?: number;
        };
        ForecastMapResponse: {
            stops: components["schemas"]["MapStopLoad"][];
            hour: number;
            meta: components["schemas"]["ForecastMeta"];
            effect?: components["schemas"]["CoefficientEffect"];
        };
        HeatmapCell: {
            stop_id: string;
            hour: number;
            value: number;
        };
        HeatmapResponse: {
            stops: {
                id: string;
                name: string;
                sequence: number;
            }[];
            cells: components["schemas"]["HeatmapCell"][];
            meta: components["schemas"]["ForecastMeta"];
        };
        KpiResponse: {
            total_passengers: number;
            peak_hour: number;
            peak_hour_load?: number;
            busiest_stop: {
                id: string;
                name: string;
                load: number;
            };
            delta_vs_baseline_percent?: number;
            meta: components["schemas"]["ForecastMeta"];
            effect?: components["schemas"]["CoefficientEffect"];
        };
        FactorPreset: {
            id: string;
            name: string;
            description?: string;
            coefficients: components["schemas"]["Coefficients"];
        };
        ExternalSource: {
            name: string;
            url: string;
            description?: string;
        };
        FactorsResponse: {
            presets: components["schemas"]["FactorPreset"][];
            sources: components["schemas"]["ExternalSource"][];
            defaults: components["schemas"]["Coefficients"];
        };
        ModelInfo: {
            name: string;
            version: string;
            /** Format: date-time */
            trained_at: string;
            wape: number;
            wape_by_horizon?: {
                [key: string]: number;
            };
            scope: string;
            limitations: string[];
        };
        RecomputeResponse: {
            job_id: string;
            status: string;
        };
        TelemetryEvent: {
            type: string;
            /** Format: date-time */
            ts: string;
            payload?: {
                [key: string]: unknown;
            };
        };
        TelemetryBatch: {
            events: components["schemas"]["TelemetryEvent"][];
        };
        UserScenario: {
            id: string;
            user_id: string;
            name: string;
            coefficients: components["schemas"]["Coefficients"];
            /** Format: date-time */
            created_at: string;
        };
        UserScenarioCreate: {
            name: string;
            coefficients: components["schemas"]["Coefficients"];
        };
        UserScenarioList: {
            items: components["schemas"]["UserScenario"][];
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Service unavailable */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        RouteId: string;
        /** @description Comma-separated route ids */
        RouteIds: string;
        Horizon: components["schemas"]["Horizon"];
        Date: string;
        DateFrom: string;
        DateTo: string;
        StopId: string;
        SegmentFrom: string;
        SegmentTo: string;
        TimeFrom: string;
        TimeTo: string;
        Grouping: components["schemas"]["Grouping"];
        Hour: number;
        /** @description Also accept k_event, k_season, k_traffic as sibling query params */
        Coefficients: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRoutes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteListResponse"];
                };
            };
        };
    };
    getRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getRouteGeometry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteGeometry"];
                };
            };
        };
    };
    getForecast: {
        parameters: {
            query: {
                /** @description Comma-separated route ids */
                route: components["parameters"]["RouteIds"];
                horizon: components["parameters"]["Horizon"];
                date?: components["parameters"]["Date"];
                date_from?: components["parameters"]["DateFrom"];
                date_to?: components["parameters"]["DateTo"];
                stop?: components["parameters"]["StopId"];
                segment_from?: components["parameters"]["SegmentFrom"];
                segment_to?: components["parameters"]["SegmentTo"];
                from?: components["parameters"]["TimeFrom"];
                to?: components["parameters"]["TimeTo"];
                grouping?: components["parameters"]["Grouping"];
                hour?: components["parameters"]["Hour"];
                /** @description Also accept k_event, k_season, k_traffic as sibling query params */
                k_weather?: components["parameters"]["Coefficients"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getForecastMap: {
        parameters: {
            query: {
                /** @description Comma-separated route ids */
                route: components["parameters"]["RouteIds"];
                horizon: components["parameters"]["Horizon"];
                date?: components["parameters"]["Date"];
                date_from?: components["parameters"]["DateFrom"];
                date_to?: components["parameters"]["DateTo"];
                hour?: components["parameters"]["Hour"];
                segment_from?: components["parameters"]["SegmentFrom"];
                segment_to?: components["parameters"]["SegmentTo"];
                /** @description Also accept k_event, k_season, k_traffic as sibling query params */
                k_weather?: components["parameters"]["Coefficients"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastMapResponse"];
                };
            };
        };
    };
    getForecastHeatmap: {
        parameters: {
            query: {
                /** @description Comma-separated route ids */
                route: components["parameters"]["RouteIds"];
                horizon: components["parameters"]["Horizon"];
                date?: components["parameters"]["Date"];
                date_from?: components["parameters"]["DateFrom"];
                date_to?: components["parameters"]["DateTo"];
                segment_from?: components["parameters"]["SegmentFrom"];
                segment_to?: components["parameters"]["SegmentTo"];
                /** @description Also accept k_event, k_season, k_traffic as sibling query params */
                k_weather?: components["parameters"]["Coefficients"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapResponse"];
                };
            };
        };
    };
    getForecastKpi: {
        parameters: {
            query: {
                /** @description Comma-separated route ids */
                route: components["parameters"]["RouteIds"];
                horizon: components["parameters"]["Horizon"];
                date?: components["parameters"]["Date"];
                date_from?: components["parameters"]["DateFrom"];
                date_to?: components["parameters"]["DateTo"];
                stop?: components["parameters"]["StopId"];
                segment_from?: components["parameters"]["SegmentFrom"];
                segment_to?: components["parameters"]["SegmentTo"];
                from?: components["parameters"]["TimeFrom"];
                to?: components["parameters"]["TimeTo"];
                hour?: components["parameters"]["Hour"];
                /** @description Also accept k_event, k_season, k_traffic as sibling query params */
                k_weather?: components["parameters"]["Coefficients"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiResponse"];
                };
            };
        };
    };
    exportForecast: {
        parameters: {
            query: {
                format: "csv" | "xlsx";
                /** @description Comma-separated route ids */
                route: components["parameters"]["RouteIds"];
                horizon: components["parameters"]["Horizon"];
                date?: components["parameters"]["Date"];
                date_from?: components["parameters"]["DateFrom"];
                date_to?: components["parameters"]["DateTo"];
                stop?: components["parameters"]["StopId"];
                segment_from?: components["parameters"]["SegmentFrom"];
                segment_to?: components["parameters"]["SegmentTo"];
                from?: components["parameters"]["TimeFrom"];
                to?: components["parameters"]["TimeTo"];
                grouping?: components["parameters"]["Grouping"];
                /** @description Also accept k_event, k_season, k_traffic as sibling query params */
                k_weather?: components["parameters"]["Coefficients"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File download */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    getFactors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactorsResponse"];
                };
            };
        };
    };
    getModelInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfo"];
                };
            };
        };
    };
    recomputeForecast: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecomputeResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    postTelemetry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelemetryBatch"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUserScenarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserScenarioList"];
                };
            };
        };
    };
    createUserScenario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserScenarioCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserScenario"];
                };
            };
        };
    };
    deleteUserScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
